"""empty message

Revision ID: b06bab878e3c
Revises: 937a802ad1ed
Create Date: 2024-09-16 21:47:13.664835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06bab878e3c'
down_revision = '937a802ad1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diet_id', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet', schema=None) as batch_op:
        batch_op.drop_column('diet_id')

    # ### end Alembic commands ###
