"""empty message

Revision ID: c82aa4431641
Revises: b06bab878e3c
Create Date: 2024-09-25 15:42:44.082711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c82aa4431641'
down_revision = 'b06bab878e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.alter_column('additional_note',
               existing_type=mysql.VARCHAR(length=225),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.alter_column('additional_note',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=225),
               existing_nullable=True)

    # ### end Alembic commands ###
